# Can be "client" or "server"
# use ntm-config -c to edit frpc.toml (client)
#  or ntm-config -s to edit frps.toml (server)

type="client"
server_token="your_token"



# # Demo Server Config
# type="server"
# server_token="your_token"
# master_port=7000



# # Demo Client Config
# type="client"
# server_token="your_token"
# client_id="your_client_id"
# server_address="1.2.3.4:7000" # optional
